### ISSUE TITLE
default fallback function

### ISSUE THREAD

**Issue by sihoang** [tomo-pool/tomo-pool#2]
Sorry if I report this immaturely, is it required to have a default fallback function?

What is the expected behavior when I just send TOMO to the tomo-pool contract? Should it reject or accept but do nothing?

**Comment by thanhson1085** [comment]
Yep, I think it should call `stake` in the default

**Comment by phamvancam2104** [comment]
The fallback was for receiving funds from TomoValidator contract (see withdraw functions).

If we would want to call stake here we need to check whether the sender is the validator contract or not. If not, then stake

**Comment by khaihkd** [comment]
We did it https://github.com/tomo-pool/tomo-pool/pull/5
